### ISSUE TITLE
datasets info

### ISSUE THREAD

**Issue by ozymand1a** [videturfortuna/vehicle_reid_itsc2023#1]
Hi!

Great work, results are solid! I want to reproduce your results but I can't find VeRi-776 dataset and annotations of VeRi-Wild.

Could you please share this data?

**Comment by videturfortuna** [comment]
Hi,

Both are available upon request at their respective GitHub pages. 
Veri776: https://vehiclereid.github.io/VeRi/
Veri-Wild: https://github.com/PKU-IMRE/VERI-Wild
