### ISSUE TITLE
veriwild directory structure

### ISSUE THREAD

**Issue by jsteinberg-rbi** [videturfortuna/vehicle_reid_itsc2023#13]
`VeRi-Wild` comes as 23 rar files as pictured below. Some rar files contain subdirectories of the same name. The `CustomDataSet4VERIWILD` extension of PyTorch's `DataSet` class takes a `ROOT_DIR` path that it expects _all_ the jpg's to be at? I'm curious how you organized your veriwild dataset without overwriting directories with the same name, e.g. `00526` which occurs twice throughout the database:

```
find veri-wild/images/ -name '05266' -type d
veri-wild/images/images.part23/images/05266
veri-wild/images/images.part03/images/05266
```

I can see ways to change the csv files to match my directory structure, but I'm wondering if you have a more expeditious solution.

<img width="1748" alt="Screenshot 2024-03-14 at 7 39 15 PM" src="https://github.com/videturfortuna/vehicle_reid_itsc2023/assets/108352663/5643bc1f-275b-4ca6-9f54-2e45762cf902">

**Comment by videturfortuna** [comment]
First you need to download the rar's and extract them all. You just need to extract with unrar, I believe something like this should work:
```
unrar x "*.*.rar"
```
You will obtain the dataset as it should be, a folder containing two folders images/ and a train_test_split/, then you should change ROOT_DIR for the "*/images/" folder, and give the .txt associated to train or test e.g. "*/train_test_split/train_list.txt".

**Comment by jsteinberg-rbi** [comment]
will prep PR for this step as I wasted a bunch of time on macos fiddling with getting the dataset right and this command is precisely what I needed to run!
