### ISSUE TITLE
Code issue in FinalLayer

### ISSUE THREAD

**Issue by Yadg** [videturfortuna/vehicle_reid_itsc2023#20]
Line 440 of models/models.py:
>  ff = self.finalblocks\[i+j\](aux_emb)

It seems that when i=0, j=1 and i=1, j=0 it uses the same finalblock.

```python
for i in range(len(x)):
    for j in range(self.n_groups):
        aux_emb = emb[:,int(2048/self.n_groups*j):int(2048/self.n_groups*(j+1))]
        if (i+j)%2==0:
            pred, ff = self.finalblocks[i+j](aux_emb)
            ffs.append(ff)
            preds.append(pred)
        else:
            ff = self.finalblocks[i+j](aux_emb)
            embs.append(aux_emb)
            ffs.append(ff)
```

**Comment by Yadg** [comment]
I modified the code to
```python
if i == 0:
    ff = self.finalblocks[i + j](aux_emb)
else:
    ff = self.finalblocks[i + j + 2](aux_emb)
```
and test with MBR_R50_2x2G:
```python
model = MBR_model(class_num=data['n_classes'], n_branches=['2x'], losses="LBS", n_groups=2, LAI=data['LAI'], n_cams=data['n_cams'], n_views=data['n_views'], x2g=True)  
```
The result is:
mAP: 0.8446
Rank-1: 0.9756
Rank-5: 0.9905

**Comment by videturfortuna** [comment]
Not the best code when I remade it. Thanks a lot and sorry for not replying, I will take it into account and refactor the code when I upload a new work with 89% mAP on ViT-B soon.

**Comment by wxk2024** [comment]
> I modified the code to
> 
> if i == 0:
>     ff = self.finalblocks[i + j](aux_emb)
> else:
>     ff = self.finalblocks[i + j + 2](aux_emb)
> and test with MBR_R50_2x2G:
> 
> model = MBR_model(class_num=data['n_classes'], n_branches=['2x'], losses="LBS", n_groups=2, LAI=data['LAI'], n_cams=data['n_cams'], n_views=data['n_views'], x2g=True)  
> The result is: mAP: 0.8446 Rank-1: 0.9756 Rank-5: 0.9905

你好可以发一下您的源代码吗，我想在自己的电脑上跑出这种精度，可有偿，邮箱 1184143982@qq.com
