### ISSUE TITLE
Compute configurations

### ISSUE THREAD

**Issue by jsteinberg-rbi** [videturfortuna/vehicle_reid_itsc2023#7]
@videturfortuna pardon my naivety but what do these column headers mean?

`4G 2G 2X2G 2X 4X`

I assume 4G is 4GB VRAM? 2G is 2GB VRAM? 2X2G is 2 GPUs in parallel each with 2GB VRAM? No idea what 2X and 4X are.

**Comment by videturfortuna** [comment]
No, please read [paper](https://ieeexplore.ieee.org/document/10422175) for more information. 
It's somewhat confusing but it's a terminology for branches by expansion or branches by grouping. 
By grouping: 4G, 2G
By expansion: 2X, 4X
with both 2x2G
